export const DEFAULT_FPS = 30;
export const DEFAULT_COMPOSITION_WIDTH = 1080;
export const DEFAULT_COMPOSITION_HEIGHT = 1920;
export const MAX_UNDO_STACK_SIZE = 50;
export const MAX_FILE_UPLOAD_SIZE_IN_MB = 1000;
export const MAX_DURATION_ALLOWING_CAPTIONING_IN_SEC = 60 * 10;
